const express = require('express');
const router = express.Router();
const { auth, requireCredits } = require('../middleware/auth.middleware');
const { generateBusiness } = require('../services/ai.service');
const Generation = require('../models/Generation.model');
const fs = require('fs');
const path = require('path');
const archiver = require('archiver');

const GENERATED_DIR = path.join(__dirname, '../../generated');

const buildStoreHTML = (biz) => {
  const products = (biz.products || []).map(p => `
    <div class="product-card">
      <div class="product-emoji">${p.emoji || '📦'}</div>
      <h3>${p.name}</h3>
      <p>${p.description}</p>
      <div class="product-footer">
        <span class="price">$${Number(p.price).toFixed(2)}</span>
        <button onclick="addCart('${p.name}')">Add to Cart</button>
      </div>
    </div>`).join('');

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${biz.name}</title>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
<style>*{margin:0;padding:0;box-sizing:border-box}:root{--p:${biz.themeColor||'#f59e0b'}}
body{font-family:'Plus Jakarta Sans',sans-serif;background:#0a0a0f;color:#f0f0f8}
nav{position:sticky;top:0;padding:1rem 2rem;background:rgba(10,10,15,.9);backdrop-filter:blur(20px);border-bottom:1px solid rgba(255,255,255,.08);display:flex;justify-content:space-between;align-items:center}
.logo{font-weight:800;font-size:1.4rem;color:var(--p)}
.hero{padding:8rem 2rem;text-align:center;background:radial-gradient(ellipse 70% 50% at 50% 0%,${biz.themeColor||'#f59e0b'}22,transparent)}
.hero h1{font-size:clamp(2.5rem,6vw,5rem);font-weight:800;margin-bottom:1.5rem}
.hero p{color:#888;font-size:1.1rem;max-width:560px;margin:0 auto 2rem}
.btn{background:var(--p);color:#000;padding:1rem 2.5rem;border-radius:50px;font-weight:700;font-size:1rem;border:none;cursor:pointer}
.products{padding:5rem 2rem;max-width:1200px;margin:0 auto}
.products h2{font-size:2rem;font-weight:800;text-align:center;margin-bottom:3rem}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:1.5rem}
.product-card{background:#111118;border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:1.75rem;transition:.2s}
.product-card:hover{border-color:var(--p);transform:translateY(-4px)}
.product-emoji{font-size:2.5rem;margin-bottom:1rem}
.product-card h3{font-weight:700;margin-bottom:.5rem}
.product-card p{color:#666;font-size:.9rem;line-height:1.6;margin-bottom:1.5rem}
.product-footer{display:flex;justify-content:space-between;align-items:center}
.price{font-size:1.3rem;font-weight:800;color:var(--p)}
.product-footer button{background:var(--p);color:#000;border:none;padding:.5rem 1.25rem;border-radius:50px;font-weight:600;cursor:pointer}
footer{padding:3rem;text-align:center;color:#444;border-top:1px solid rgba(255,255,255,.05)}
.toast{position:fixed;bottom:2rem;right:2rem;background:#111;border:1px solid var(--p);color:#fff;padding:1rem 1.5rem;border-radius:12px;transform:translateY(100px);transition:.3s;z-index:999}
.toast.show{transform:translateY(0)}</style></head>
<body>
<nav><div class="logo">${biz.name}</div><button class="btn" style="padding:.5rem 1.25rem">Shop Now</button></nav>
<section class="hero"><h1>${biz.name}</h1><p>${biz.tagline}</p><button class="btn">Browse Products →</button></section>
<section class="products"><h2>Our Products</h2><div class="grid">${products}</div></section>
<footer><p>© 2024 ${biz.name}. Generated by Double Eight AI.</p></footer>
<div class="toast" id="toast">Added to cart!</div>
<script>function addCart(n){const t=document.getElementById('toast');t.textContent='🛒 '+n+' added!';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}</script>
</body></html>`;
};

router.post('/generate', auth, requireCredits(5), async (req, res) => {
  try {
    const { idea, category = 'ecommerce' } = req.body;
    if (!idea?.trim()) return res.status(400).json({ success: false, message: 'Idea required' });
    
    const biz = await generateBusiness(idea, category);
    
    // Generate store files
    const genId = Date.now().toString();
    const dir = path.join(GENERATED_DIR, genId);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'index.html'), buildStoreHTML(biz));
    fs.writeFileSync(path.join(dir, 'README.md'), `# ${biz.name}\n\n${biz.tagline}\n\n## Products\n${(biz.products||[]).map(p=>`- **${p.name}** $${p.price}: ${p.description}`).join('\n')}`);
    
    // Create ZIP
    const zipPath = path.join(GENERATED_DIR, `${genId}.zip`);
    await new Promise((resolve, reject) => {
      const output = fs.createWriteStream(zipPath);
      const archive = archiver('zip', { zlib: { level: 9 } });
      output.on('close', resolve);
      archive.on('error', reject);
      archive.pipe(output);
      archive.directory(dir, false);
      archive.finalize();
    });
    
    await req.user.useCredits(5);
    
    const gen = await Generation.create({
      userId: req.user._id, type: 'business', title: biz.name, category,
      input: idea, output: biz, creditsUsed: 5, isSaved: true, status: 'completed',
      downloadUrl: `/generated/${genId}.zip`, zipPath,
      metadata: { genId, themeColor: biz.themeColor },
    });
    
    res.json({ success: true, business: biz, generationId: gen._id, downloadUrl: `http://localhost:5000/generated/${genId}.zip`, credits: req.user.credits });
  } catch (e) { console.error(e); res.status(500).json({ success: false, message: e.message }); }
});

router.get('/categories', auth, (req, res) => {
  res.json({ success: true, categories: [
    { id: 'ecommerce', label: 'Ecommerce Store', icon: '🛍️', credits: 5 },
    { id: 'agency', label: 'Agency', icon: '🏢', credits: 5 },
    { id: 'saas', label: 'SaaS Product', icon: '⚙️', credits: 5 },
    { id: 'local', label: 'Local Business', icon: '📍', credits: 5 },
    { id: 'dropshipping', label: 'Dropshipping', icon: '📦', credits: 5 },
    { id: 'ai-startup', label: 'AI Startup', icon: '🤖', credits: 5 },
  ]});
});

module.exports = router;
