// Export Service — generates PDF, DOCX, PPTX from markdown/text content
// Uses pdfmake, docx, pptxgenjs

function buildPDFDoc(title, content, subtitle) {
  // Convert markdown to pdfmake content blocks
  const lines = content.split('\n');
  const body = [];

  body.push({
    canvas: [{ type: 'rect', x: 0, y: 0, w: 515, h: 80, r: 8, color: '#0c0c18' }]
  });
  body.push({ text: 'DOUBLE EIGHT AI', style: 'logoText', margin: [0, -65, 0, 0] });
  body.push({ text: title, style: 'docTitle', margin: [0, 8, 0, 4] });
  if (subtitle) body.push({ text: subtitle, style: 'docSubtitle' });
  body.push({ text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), style: 'docDate' });
  body.push({ canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#c9a84c' }], margin: [0, 16, 0, 24] });

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) { body.push({ text: '', margin: [0, 4] }); continue; }
    if (trimmed.startsWith('## ')) {
      body.push({ text: trimmed.slice(3), style: 'h2', margin: [0, 16, 0, 6] });
    } else if (trimmed.startsWith('### ')) {
      body.push({ text: trimmed.slice(4), style: 'h3', margin: [0, 10, 0, 4] });
    } else if (trimmed.startsWith('# ')) {
      body.push({ text: trimmed.slice(2), style: 'h1', margin: [0, 20, 0, 8] });
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      body.push({ text: '• ' + trimmed.slice(2), style: 'bullet', margin: [12, 2, 0, 2] });
    } else if (/^\d+\. /.test(trimmed)) {
      body.push({ text: trimmed, style: 'bullet', margin: [12, 2, 0, 2] });
    } else if (trimmed.startsWith('**') && trimmed.endsWith('**')) {
      body.push({ text: trimmed.replace(/\*\*/g, ''), bold: true, style: 'body', margin: [0, 2] });
    } else {
      // Strip inline markdown
      const clean = trimmed.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`(.+?)`/g, '$1');
      body.push({ text: clean, style: 'body', margin: [0, 2] });
    }
  }

  body.push({ canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 1, lineColor: '#1a1a2e' }], margin: [0, 24, 0, 8] });
  body.push({ text: 'Generated by Double Eight AI — doubleightal.com', style: 'footer' });

  return {
    content: body,
    styles: {
      logoText: { fontSize: 9, color: '#c9a84c', letterSpacing: 3, bold: true, alignment: 'center' },
      docTitle: { fontSize: 22, bold: true, color: '#f0eff8', alignment: 'center' },
      docSubtitle: { fontSize: 13, color: '#9898b8', alignment: 'center' },
      docDate: { fontSize: 10, color: '#505070', alignment: 'center', margin: [0, 4, 0, 0] },
      h1: { fontSize: 18, bold: true, color: '#f0eff8' },
      h2: { fontSize: 14, bold: true, color: '#c9a84c' },
      h3: { fontSize: 12, bold: true, color: '#a09bfc' },
      body: { fontSize: 10, color: '#c0c0d8', lineHeight: 1.6 },
      bullet: { fontSize: 10, color: '#c0c0d8', lineHeight: 1.5 },
      footer: { fontSize: 8, color: '#303050', alignment: 'center', italics: true }
    },
    defaultStyle: { font: 'Helvetica', fontSize: 10, color: '#c0c0d8' },
    pageMargins: [40, 40, 40, 40],
    background: (currentPage) => ({
      canvas: [{ type: 'rect', x: 0, y: 0, w: 595.28, h: 841.89, color: '#030305' }]
    })
  };
}

async function generatePDF(title, content, subtitle) {
  const PdfPrinter = require('pdfmake');
  const fonts = {
    Helvetica: {
      normal: 'Helvetica', bold: 'Helvetica-Bold',
      italics: 'Helvetica-Oblique', bolditalics: 'Helvetica-BoldOblique'
    }
  };
  const printer = new PdfPrinter(fonts);
  const docDef = buildPDFDoc(title, content, subtitle);
  const doc = printer.createPdfKitDocument(docDef);
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

async function generateDOCX(title, content) {
  const { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Packer } = require('docx');
  const lines = content.split('\n');
  const children = [];

  children.push(new Paragraph({
    children: [new TextRun({ text: 'DOUBLE EIGHT AI', bold: true, color: 'C9A84C', size: 16 })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 100 }
  }));
  children.push(new Paragraph({
    text: title,
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 }
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), color: '666666', size: 18 })],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 }
  }));

  for (const line of lines) {
    const t = line.trim();
    if (!t) { children.push(new Paragraph({ text: '' })); continue; }
    if (t.startsWith('## ')) {
      children.push(new Paragraph({ text: t.slice(3), heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 100 } }));
    } else if (t.startsWith('### ')) {
      children.push(new Paragraph({ text: t.slice(4), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 } }));
    } else if (t.startsWith('# ')) {
      children.push(new Paragraph({ text: t.slice(2), heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } }));
    } else if (t.startsWith('- ') || t.startsWith('* ')) {
      children.push(new Paragraph({ text: t.slice(2), bullet: { level: 0 }, spacing: { after: 60 } }));
    } else {
      const clean = t.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`(.+?)`/g, '$1');
      children.push(new Paragraph({ children: [new TextRun({ text: clean, size: 22 })], spacing: { after: 80 } }));
    }
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
    styles: {
      paragraphStyles: [{
        id: 'Normal', name: 'Normal', run: { font: 'Calibri', size: 22, color: '333333' }
      }]
    }
  });
  return Packer.toBuffer(doc);
}

async function generatePPTX(title, content, subtitle) {
  const pptx = new (require('pptxgenjs'))();
  pptx.layout = 'LAYOUT_16x9';
  pptx.theme = { headFontFace: 'Arial', bodyFontFace: 'Arial' };

  // Cover slide
  const cover = pptx.addSlide();
  cover.background = { color: '030305' };
  cover.addShape(pptx.ShapeType.rect, { x: 0, y: 3.5, w: 10, h: 0.04, fill: { color: 'C9A84C' } });
  cover.addText('DOUBLE EIGHT AI', { x: 0.5, y: 0.4, w: 9, h: 0.4, fontSize: 11, color: 'C9A84C', bold: true, charSpacing: 5 });
  cover.addText(title, { x: 0.5, y: 1.2, w: 9, h: 1.8, fontSize: 32, color: 'F0EFF8', bold: true, align: 'left', wrap: true });
  if (subtitle) cover.addText(subtitle, { x: 0.5, y: 3.1, w: 9, h: 0.5, fontSize: 14, color: '9898B8' });
  cover.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' }), { x: 0.5, y: 4.0, w: 9, h: 0.35, fontSize: 11, color: '505070' });

  // Parse content into slides
  const sections = content.split(/^## /m).filter(s => s.trim());
  sections.forEach((section, i) => {
    const sLines = section.split('\n');
    const sTitle = sLines[0].trim();
    const sBody = sLines.slice(1).join('\n').trim();
    const slide = pptx.addSlide();
    slide.background = { color: '07070F' };
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.08, h: 5.63, fill: { color: 'C9A84C' } });
    slide.addText(`0${i + 1}`, { x: 0.2, y: 0.3, w: 0.8, h: 0.4, fontSize: 11, color: 'C9A84C', bold: true });
    slide.addText(sTitle, { x: 0.3, y: 0.7, w: 9.4, h: 0.7, fontSize: 22, color: 'F0EFF8', bold: true });
    slide.addShape(pptx.ShapeType.line, { x: 0.3, y: 1.45, w: 9.2, h: 0, line: { color: '1A1A2E', width: 1 } });
    const bullets = sBody.split('\n').filter(l => l.trim()).slice(0, 8).map(l =>
      l.replace(/^[-*]\s*/, '').replace(/\*\*(.+?)\*\*/g, '$1').replace(/`(.+?)`/g, '$1').trim()
    ).filter(Boolean);
    if (bullets.length) {
      slide.addText(bullets.map(b => ({ text: b, options: { bullet: { code: '2022' }, indentLevel: 0 } })), {
        x: 0.4, y: 1.6, w: 9.2, h: 3.7, fontSize: 13, color: 'C0C0D8', lineSpacingMultiple: 1.5
      });
    }
    slide.addText('Double Eight AI', { x: 0.3, y: 5.2, w: 9, h: 0.3, fontSize: 9, color: '303050', align: 'right' });
  });

  return pptx.write({ outputType: 'nodebuffer' });
}

// Simple HTML export (always available as fallback)
function generateHTML(title, content, subtitle) {
  const processed = content
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*?<\/li>\n?)+/gs, '<ul>$&</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>${title} — Double Eight AI</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',sans-serif;background:#030305;color:#e0e0f0;line-height:1.8;-webkit-print-color-adjust:exact;print-color-adjust:exact}
.cover{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:60px 40px;background:radial-gradient(ellipse 80% 60% at 50% 0%,rgba(201,168,76,0.1),transparent 60%)}
.logo{font-size:10px;letter-spacing:5px;color:#c9a84c;text-transform:uppercase;margin-bottom:32px}
.cover-title{font-size:2.8rem;font-weight:800;margin-bottom:12px;color:#fff}
.cover-sub{font-size:15px;color:#9898b8;margin-bottom:32px}
.cover-date{font-size:11px;color:#505070;letter-spacing:2px}
.divider{border:none;border-top:1px solid #c9a84c;margin:40px 0;opacity:.3}
.page{max-width:860px;margin:0 auto;padding:60px 40px 80px}
h1{font-size:2rem;color:#fff;margin:32px 0 12px}
h2{font-size:1.3rem;color:#c9a84c;margin:28px 0 10px;padding-bottom:8px;border-bottom:1px solid rgba(201,168,76,.15)}
h3{font-size:1.05rem;color:#a09bfc;margin:20px 0 8px}
p{margin:8px 0;color:#c0c0d8}
ul{margin:8px 0 8px 20px;color:#c0c0d8}
li{margin:4px 0}
strong{color:#fff}
em{color:#a09bfc}
code{background:rgba(255,255,255,.06);padding:2px 7px;border-radius:4px;font-family:monospace;font-size:.9em;color:#c9a84c}
.footer{text-align:center;margin-top:60px;padding-top:20px;border-top:1px solid rgba(255,255,255,.05);font-size:11px;color:#303050;letter-spacing:2px}
@media print{body{background:#030305}.cover{min-height:auto;padding:40px}}
</style></head><body>
<div class="cover">
<div class="logo">Double Eight AI · Business Intelligence</div>
<h1 class="cover-title">${title}</h1>
${subtitle ? `<p class="cover-sub">${subtitle}</p>` : ''}
<div class="cover-date">${new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}</div>
</div>
<div class="page"><p>${processed}</p>
<div class="footer">DOUBLE EIGHT AI · CONFIDENTIAL</div>
</div></body></html>`;
}

module.exports = { generatePDF, generateDOCX, generatePPTX, generateHTML };
